Extra login google
wolox-training/fs-android pull request #20
Opened 2019-08-05 14:52 UTC by FedericoSanucciWX

### Description
Extras - Google Login. User now can login through google. The app validates from user credentials and from google to do autoLogin

### Screenshot
![Extras-Google-001](https://user-images.githubusercontent.com/53021434/62473588-6c735600-b777-11e9-8591-7c0f41b898e7.png)
![Extras-Google-002](https://user-images.githubusercontent.com/53021434/62473589-6c735600-b777-11e9-97ab-cac414cedfb0.png)

### Trello
https://trello.com/c/vgTTeqCo/36-google-login

2019-08-06 16:59 UTC, FedericoSanucciWX commented
Google login's logic done with an adapter

2019-08-07 17:28 UTC, dylan-muszel requested changes
Some comments about the adapter. If you have any question, feel free to ask 😄

2019-08-07 17:28 UTC, dylan-muszel commented on app/src/main/java/ar/com/wolox/android/training/ui/training/login/LoginFragment.java
> +        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
You could (and you should I think, since you already have it) add this to the adapter.

2019-08-07 17:28 UTC, dylan-muszel commented on app/src/main/java/ar/com/wolox/android/training/ui/training/login/LoginFragment.java
> +        return GoogleSignIn.getLastSignedInAccount(Objects.requireNonNull(getContext()));
This should be on the adapter.

2019-08-07 17:28 UTC, dylan-muszel commented on app/src/main/java/ar/com/wolox/android/training/ui/training/login/LoginGoogleAdapter.java
> +package ar.com.wolox.android.training.ui.training.login;
😮 Do this with Kotlin!!!

2019-08-07 17:28 UTC, dylan-muszel commented on app/src/main/java/ar/com/wolox/android/training/ui/training/login/LoginPresenter.java
> +                    new Handler().postDelayed(() -> getView().hideAnimations(), DELAY);
Why're you using the `Handler`?

2019-08-08 12:53 UTC, FedericoSanucciWX commented
LoginGoogleAdapter in kotlin

2019-08-08 15:23 UTC, dylan-muszel approved these changes
![](https://media0.giphy.com/media/t1lmQR7sXeZJC/giphy.gif)

Very good work!

2019-08-09 14:48 UTC, merged